version: '3.4'

x-build:
  - &build-args
    APP_ENV: 'production'
    APP_DEBUG: 'false'
  - &build-cache
    - ${PHP_IMAGE:-vuongxuongminh/docker-helm-laravel-php}:production
    - ${NGINX_IMAGE:-vuongxuongminh/docker-helm-laravel-nginx}:production

services:
  fpm:
    image: ${PHP_IMAGE:-vuongxuongminh/docker-helm-laravel-php}:production
    build:
      cache_from: *build-cache
      args:
        << : *build-args

  supervisor:
    image: ${PHP_IMAGE:-vuongxuongminh/docker-helm-laravel-php}:production
    build:
      cache_from: *build-cache
      args:
        << : *build-args

  nginx:
    image: ${NGINX_IMAGE:-vuongxuongminh/docker-helm-laravel-nginx}:production
    build:
      cache_from: *build-cache
      args:
        << : *build-args