version: '3.4'

x-build:
  - &build-args
    APP_ENV: 'prod'
    APP_DEBUG: 'false'
  - &build-cache
    - ${PHP_IMAGE:-vuongxuongminh/docker-helm-laravel-php}:prod
    - ${NGINX_IMAGE:-vuongxuongminh/docker-helm-laravel-nginx}:prod

services:
  fpm:
    image: ${PHP_IMAGE:-vuongxuongminh/docker-helm-laravel-php}:prod
    build:
      cache_from: *build-cache
      args:
        << : *build-args

  supervisor:
    image: ${PHP_IMAGE:-vuongxuongminh/docker-helm-laravel-php}:prod
    build:
      cache_from: *build-cache
      args:
        << : *build-args

  nginx:
    image: ${NGINX_IMAGE:-vuongxuongminh/docker-helm-laravel-nginx}:prod
    build:
      cache_from: *build-cache
      args:
        << : *build-args